bankproject/bankapp/urls.py
from . import views
from django.urls import path
app_name='bankapp'
urlpatterns = [

    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('form',views.form,name='form'),
    path('home',views.home,name='home'),
    path('logout',views.logout,name='logout'),
    path('link',views.link,name='link'),




]

bankproject/bankproject/urls.py
from django.conf import settings
from django.contrib import admin

from django.conf.urls.static import static

from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),

]


if settings.DEBUG:
     urlpatterns+=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
     urlpatterns+=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

bankproject/bankapp/models.py
from django.db import models


class Task(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    img=models.ImageField(upload_to='img')
def __str__(self):
    return self.name

bankproject/bankapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect


def  register(request):


    return render(request,"register.html")


def login(request):

    return render(request,"login.html")






def form(request):
    return render(request,"form.html")
def logout(request):
    return render(request,"logout.html")

def home(request):
    return render(request,"home.html")
def link(request):
    return render(request,"link.html")
    return redirect('/')

bankproject/bankapp/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src= "https://kit.fontawesome.com/cae219a7d3.js"> </script>

   <meta name="description" content="{% block metadescription %} {% endblock %}" >


    <title>{% block title %} {% endblock %}</title>
</head>
<body>




{% include 'navbar.html' %}
    <br>
    <br>





     <script src="{% static 'js/popper.min.js' %}"> </script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

bankproject/bankapp/templates/form.html
{% load static %}<br>
REGISTRATION FORM

    <link href="{% static 'css/reg.css' %}" rel="stylesheet">
<form action="register" method="Post">
  {% csrf_token %}
 <br>
 <br>

 NAME: <input type="text" name="name" placeholder="Enter your Name"><br>
 <br>
   DOB:<input type="date" name="DOB" placeholder="Enter your dob"><br>
 <br>
    AGE:<input type="number" name="age" placeholder="Enter your age"><br>
 <br>
    GENDER:<input type="text" name="gender" placeholder="male or female"><br>
 <br>
    PHONENO:<input type="number" name="phonenumber" placeholder="Enter phonenumber"><br>
 <br>
    ADDRESS:<input type="text" name="address" placeholder="Enter address"><br>
 <br>
    DISTRICT:<input type="text" name="district" placeholder="Enter district"><br>
 <br>
    BRANCH:<input type="search" name="branch" placeholder="Enter branch name"><br>
 <br>
    ACCOUNT TYPE:<input type="text" name="account type"placeholder="Enter account type"><br>
 <br>
    MATERIALS PROVIDED:<br><br>Cheque book <input type="checkbox" name="materials provide" placeholder="enter name of materials provided"><br>
 <br> Credit card<input type="checkbox" name="materials provide" placeholder="enter name of materials provided"><br>
 <br>Debit Card<input type="checkbox" name="materials provide" placeholder="enter name of materials provided"><br>
 <br>
    <input type="submit">
    <input type="button" name="login">
</form>

bankproject/bankapp/templates/header.html
{% extends 'base.html' %}
<header xmlns="http://www.w3.org/1999/html">
    <center>

    <a href=""><img src="{% static 'c1.png' %}" alt="">
    </a>
    </center>
    </header>

bankproject/bankapp/templates/home.html
{% extends 'base.html' %}

bankproject/bankapp/templates/image.html
{% extends 'base.html' %}
{% load static %}
<div>
<img src="{% static 'img/ben.png' %}" >
</div>
<br>

bankproject/bankapp/templates/link.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<link href="{% static 'css/log.css' %}" rel="stylesheet">
<br>
<br>
<h2> Your Application is successfully accepted</h2>
<br>
<br>
<br>
<a href="{% url 'bankapp:home' %}"><h1>Home</h1> </a>
</body>
</html>

bankproject/bankapp/templates/login.html
{% load static %}


<div class="container">
	<div class="screen">
		<div class="screen__content">
                <link href="{% static 'css/style.css' %}" rel="stylesheet">
			<form class="login">
				<div class="login__field">
					<i class="login__icon fas fa-user"></i>
					<input type="text" class="login__input" placeholder="User name / Email">
				</div>
				<div class="login__field">
					<i class="login__icon fas fa-lock"></i>
					<input type="password" class="login__input" placeholder="Password">
				</div>

				<button class="button login__submit">
					<span class="button__text">Log In Now</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>
			</form><a class="btn btn-warning" href="{% url 'bankapp:register' %}"> Register </a>

			<div class="social-login">

				<div class="social-icons">
					<a href="#" class="social-login__icon fab fa-instagram"></a>
					<a href="#" class="social-login__icon fab fa-facebook"></a>
					<a href="#" class="social-login__icon fab fa-twitter"></a>
				</div>
			</div>
		</div>

		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div></link>

bankproject/bankapp/templates/logout.html
{% load static %}
<link href="{% static 'css/log.css' %}" rel="stylesheet">
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1>You are successfully loggedout.</h1>
<br>
<br>
<h2>Thankyou..</h2><br>
<br>
<h3>Visit again . . .</h3>

bankproject/bankapp/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bank</title>
<nav class="navbar navbar-dark bg-dark">

  <a class="navbar-brand" href="#">
      <br>

    Indian Bank
<br>
      <br>
<a class="btn btn-warning" href="{% url 'bankapp:login' %}"> Login </a>
 <a class="btn btn-warning" href="{% url 'bankapp:register' %}"> Register</a>
  <a class="btn btn-danger" href="{% url 'bankapp:logout' %}">Logout</a>
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
    Branches
  </button>
  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">

      <li> <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kochi">KOCHI</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Aluva">ALUVA</a></li>
      <li> <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Angamaly"> ANGAMALY</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kakkanad">KAKKANAD</a></li>
      <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Vyttila">VYTTILA</a></li>


  </ul>
</div>

  </a>
</nav>



     <div class="bg-image d-flex justify-content-center align-items-center"
  style="
    background-image: url('https://mdbcdn.b-cdn.net/img/new/fluid/nature/015.webp');
    height: 100vh;
  ">


<br>
         <br>
         <br>

    <h4 class="text-white">  Indian Bank
        <br>
    </h4>
         <a class="" href="{% url 'bankapp:link' %}"><h3>Click here...<br>
             <br>
             To accept the application

         </h3></a>
</div>
<!-- Background image -->
</head>
<body>











{% block body %}
{%  endblock %}
</body>
</html>

bankproject/bankapp/templates/register.html
{% load static %}

    <div class="container">
        <div class="row">
              <link href="{% static 'css/text.css' %}" rel="stylesheet">
            <div class="col-lg-3 col-md-2"></div>
            <div class="col-lg-6 col-md-8 login-box">
                <div class="col-lg-12 login-key">
                    <i class="fa fa-key" aria-hidden="true"></i>
                </div>
                <div class="col-lg-12 login-title">
                    REGISTER
                </div>

                <div class="col-lg-12 login-form">
                    <div class="col-lg-12 login-form">
                        <form>
                            <div class="form-group">
                                <label class="form-control-label">USERNAME</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">PASSWORD</label>
                                <input type="password" class="form-control" i>
                            </div>
                            <div class="form-group">
                                <label class="form-control-label">CONFIRM PASSWORD</label>
                                <input type="password" class="form-control" i>
                            </div>
                            <div class="col-lg-12 loginbttm">
                                <div class="col-lg-6 login-btm login-text">
                                    <!-- Error Message -->
                                </div>
                                <div class="col-lg-6 login-btm login-button">
                                    <button type="submit" class="btn btn-outline-primary">LOGIN</button>
                                    <a class="btn btn-danger" href="{% url 'bankapp:form' %}"> Registration form </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>



                <div class="col-lg-3 col-md-2"></div>
            </div>
        </div>